variables:

  IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"

  DEPLOY_DIR: "/opt/todo-app"
stages:
  - build
  - deploy

# -------------------
backend_build:
  stage: build

  before_script:
    - export PATH=$HOME/.local/bin:$PATH
  script:
    - echo "Logging in to AWS ECR"
    - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REPO"
    - echo "Building backend Docker image"
    - docker build -t "$ECR_BACKEND:$IMAGE_TAG" -f ./flask/Dockerfile flask/
    - docker push "$ECR_BACKEND:$IMAGE_TAG"

  tags:
    - bastion-runner
# -------------------
frontend_build:
  stage: build

  before_script:
    - export PATH=$HOME/.local/bin:$PATH
  script:
    - echo "Logging in to AWS ECR"
    - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REPO"
    - echo "Building frontend Docker image"
    - docker build -t "$ECR_FRONTEND:$IMAGE_TAG" -f ./react/Dockerfile react/
    - docker push "$ECR_FRONTEND:$IMAGE_TAG"

  tags:
    - bastion-runner
# -------------------
deploy_staging:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  before_script:
    - export IMAGE_TAG="$IMAGE_TAG"
    - export DEPLOY_DIR="$DEPLOY_DIR"
    - export AWS_DEFAULT_REGION="$AWS_REGION"
    - export ECR_BACKEND="$ECR_BACKEND"
    - export ECR_FRONTEND="$ECR_FRONTEND"
    - export SQLALCHEMY_DATABASE_URI="$SQLALCHEMY_DATABASE_URI"
    - export JWT_SECRET_KEY="$JWT_SECRET_KEY"
    - export LT_VERSION="$LT_VERSION"
    - export ASG_NAME="$ASG_NAME"
  script:
  - |
    # Render template
    cat ./user_data.sh.tmpl \
      | sed "s|{{IMAGE_TAG}}|$IMAGE_TAG|g" \
      | sed "s|{{ECR_REPO}}|$ECR_REPO|g" \
      | sed "s|{{DEPLOY_DIR}}|$DEPLOY_DIR|g" \
      | sed "s|{{ECR_BACKEND}}|$ECR_BACKEND|g" \
      | sed "s|{{ECR_FRONTEND}}|$ECR_FRONTEND|g" \
      | sed "s|{{SQLALCHEMY_DATABASE_URI}}|$SQLALCHEMY_DATABASE_URI|g" \
      | sed "s|{{JWT_SECRET_KEY}}|$JWT_SECRET_KEY|g" \
      > user-data.sh

      # Base64 encode
      USER_DATA_B64=$(base64 < user-data.sh | tr -d '\n')

      # Get the golden launch template data
      LT_DATA=$(aws ec2 describe-launch-template-versions \
        --launch-template-id "$LT_VERSION" \
        --versions 34 \
        --query 'LaunchTemplateVersions[0].LaunchTemplateData' \
        --output json)

      # Add new UserData to LaunchTemplateData
      LT_DATA_WITH_UD=$(
        echo "$LT_DATA" \
        | jq --arg ud "$USER_DATA_B64" '.UserData = $ud'
      )
      
      # Create new launch template version
      NEW_VERSION=$(aws ec2 create-launch-template-version \
        --launch-template-id "$LT_VERSION" \
        --launch-template-data "$LT_DATA_WITH_UD" \
        --query 'LaunchTemplateVersion.VersionNumber' \
        --output text)
      
      echo "Created launch template version $NEW_VERSION"
      
      echo "ASG after update:"
      aws autoscaling describe-auto-scaling-groups \
        --auto-scaling-group-names "$ASG_NAME" \
        --query 'AutoScalingGroups[0].{LT:LaunchTemplate,IR:NewInstancesProtectedFromScaleIn}' \
        --output json

      echo "Checking existing instance refreshes..."
      aws autoscaling describe-instance-refreshes \
        --auto-scaling-group-name "$ASG_NAME" \
        --max-records 5

      echo "Starting instance refresh..."
      aws autoscaling start-instance-refresh \
        --auto-scaling-group-name "$ASG_NAME" \
        --preferences '{"MinHealthyPercentage":80}' \
        --strategy Rolling

      echo "Instance refresh started"
      
  tags:
    - bastion-runner